# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97fce642c3852f596e80ebd7d2641a0020e9c732fd07441b25603df14caf808d668e70b40d7e1e702aeecb283d0a8881d126fc07fce1d1d62eba5b64ae21f6a

test:
  secret_key_base: 1a8e0d89737f55745405645e3b753fbe4cfd3ee6619e4eedfee6925e2caa0614f9685416699fcb2df5ccec94fe24932fbd9fc9c2e31f4410bf2b046b61fe5c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
